### PR TITLE
release/11.3.1

### LINKED ISSUE #290: cookieName to be generated according to the IP protocol http or https

### LINKED ISSUE #292: Authorization middleware should wait for the whole file before responding.
Currently we will respond immediately after the header is received. This breaks the other side of the connection if it is sending big payloads.

### LINKED ISSUE #295: local login as _ADMIN fails for empty request

### LINKED ISSUE #297: Login with the Cookie

### LINKED ISSUE #299: _ADMIN account vulnerable to account lockout
Allow for IP address whitelisting

### PR DESCRIPTION
**Pull request by southbite**
- fixes #290 cookie name appended with _https if protocol is https
  - feature login with cookie fixes #297
  - possible breaking: stats now only being created if emit:true in config (no-one really uses the stats...)
  - fixes #292 - eat the rest of the post after sending an unauthorized/forbidden
  - fixes #295 - _ADMIN user locked out of web requests causes crash
  - feature: IP address whitelisting fixes #299

### CODE REVIEW

File: lib/services/security/service.js [hunk 1]
```diff
@@ -774,10 +774,17 @@ function tokenFromRequest(req, options) {
...
+  if (!options.cookieName) options.cookieName = this.config.cookieName || 'happn_token';
 
+  let token = req.cookies.get(
+    req.headers['x-forwarded-proto'] === 'https' || req.connection.encrypted
+      ? `${options.cookieName}_https`
+      : options.cookieName
+  );
+  if (token) return token;
+
+  //fall back to the old cookie name, for backward compatibility - old browsers
```
Comment (southbite) [inline lib/services/security/service.js:786]: Do we need to do this, I can see old unrefreshed browsers breaking if we don't (once they all refresh we should be ok)

File: test/integration/client/cookie-tls-proxy.js [hunk 2]
```diff
@@ -0,0 +1,90 @@
...
+          resolve();
+        } catch (e) {
+          reject(e);
+        }
+      });
+    });
+  }
+
+  function connectClient(opts) {
+    process.env['NODE_TLS_REJECT_UNAUTHORIZED'] = 0;
```
Comment (southbite) [inline test/integration/client/cookie-tls-proxy.js:82]: This is going to be ignored in future releases of node - do we want to do register a certificate and do some kind and do some magic to make this ok?

File: test/__fixtures/node-proxy/proxy.js [hunk 3]
```diff
@@ -0,0 +1,29 @@
...
+  .option("-l, --listen [listen]", "Listen port")
+  .option("-s, --secure [secure]", "Secure")
+  .parse(process.argv);
+
+let host = program.host || 'localhost';
+let port = program.port || 55000;
+let listen = program.listen || 11235;
+let secure = program.secure || false;
+
+const proxyConfig = {target:`ws://${host}:${port}`, ws: true, xfwd: true};
```
Comment (southbite) [inline test/__fixtures/node-proxy/proxy.js:17]: Note the xfwd:true - that is what you need to implement on the secure gateway

File: lib/client.js [hunk 4]
```diff
@@ -582,18 +582,19 @@
     }
   });
 
+  HappnClient.prototype.__writeCookie = function(session, sessionDocument) {
+    var cookieName = session.cookieName || 'happn_token';
+    if (this.options.protocol === 'https') cookieName += '_https';
```
Comment (HaroldStruwig) [inline lib/client.js:587]: This will have backwards compatibility issues with frontend code expecting a certain cookie name - on SMC Cloud the cookie name is 'FieldPoPDeviceCloud' and it is used in its frontend code in some places. I think this must be a option we enable - ideally server side.

File: lib/services/security/service.js (hunk 1 above)
Comment (HaroldStruwig) [reply lib/services/security/service.js:786]: I think we can leave this out unless someone else feels strong about it.

File: test/__fixtures/node-proxy/proxy.js (hunk 3 above)
Comment (HaroldStruwig) [reply test/__fixtures/node-proxy/proxy.js:17]: Noted thanks!

File: test/integration/client/cookie-tls-proxy.js (hunk 2 above)
Comment (HaroldStruwig) [reply test/integration/client/cookie-tls-proxy.js:82]: we can create a self signed cert and make it trusted by the client by giving it the ca cert - let me know if you need some help on this.

File: lib/services/security/service.js (hunk 1 above)
Comment (JohanvdWest) [reply lib/services/security/service.js:786]: All that will happen is that they will have to login again?

File: lib/client.js (hunk 4 above)
Comment (JohanvdWest) [reply lib/client.js:587]: Can session creation in this line not decide whether to add the _https or not when it responds:
https://github.com/happner/happn-3/blob/ce1fee5a084d0b6782c983494f61acb3751913f6/lib/services/security/service.js#L1302

Then we always just work with the cookieName as detected when the session is created.

We have to add a new config parameter, something like cookieNameAppendProtocol, to decide whether to append the https or not. This has to default to false.

The session creation must then check the protocol AND whether cookieNameAppendProtocol is set.

File: lib/services/security/service.js (hunk 1 above)
Comment (southbite) [reply lib/services/security/service.js:787]: I think we should just leave it in unless you guys see a security issue there?

File: lib/client.js (hunk 4 above)
Comment (southbite) [reply lib/client.js]: this has been done, kind of, instead of pushing the final cookieName to the client, the httpsCookie configuration setting is pushed to the client, which then decides to append https or not, based on whether the client is connecting via HTTP or https, httpsCookie is false by default

Comment (southbite) [reply lib/client.js]: This has been done, fully
